name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: GTEST_OUTPUT=xml:build/test-results/ GTEST_COLOR=1 make test

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: build/test-results/**/*.xml
